# Generated by Django 3.1.5 on 2021-01-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='this is mandatory', max_length=12)),
                ('description', models.TextField()),
                ('posted_at', models.DateTimeField()),
            ],
        ),
    ]
