# Generated by Django 3.1.5 on 2021-01-22 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=23, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=23)),
                ('postby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.entry')),
            ],
        ),
    ]
